# Site settings
title: Modeling and Simulation of Techno-Social Systems
description: >-
  Modeling and Simulation of Techno-Social Systems is a research unit of the
  Digital Society Center at Fondazione Bruno Kessler, Trento, Italy.
baseurl: ""
url: "https://fbk-most.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag


# Manage automatic collections
collections:
  pages:
    output: true
  people:
    output: true
    permalink: /people/:name/
  events:
    output: true
